apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql-replicaset.fullname" . }}
  labels:
    app: {{ template "postgresql-replicaset.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.password }}
  password:  {{ .Values.password | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.masterPassword }}
  masterPassword:  {{ .Values.masterPassword | b64enc | quote }}
  {{ else }}
  masterPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.rootPassword }}
  rootPassword:  {{ .Values.rootPassword | b64enc | quote }}
  {{ else }}
  rootPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
