kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ template "postgresql-replicaset.fullname" . }}-CR
rules:
    - apiGroups: [""]
      resources: ["pods"]
      resourceNames: [{{template "postgresql-replicaset.fullname" .}}-0]
      verbs: ["get","patch"]

{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceAccount.name}}
{{- end}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "postgresql-replicaset.fullname" . }}-CRB
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceAccount.name}}
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ template "postgresql-replicaset.fullname" . }}-CR
  apiGroup: rbac.authorization.k8s.io
